---
# tasks file for initialise-swarm
- name: 'Check if swarm has already been initialised'
  shell: docker node ls
  register: swarm_status
  ignore_errors: true

- name: 'Install swarm module requirements'
  pip: 
    name: docker-py
  
- name: 'Initialise swarm'
  shell: docker swarm init 
  when: swarm_status.rc !=0
  run_once: true

- name: "Retrieving swarm info"
  docker_swarm_info:
  register: swarm_info

- name: Deploy stack from docker-compose file
  docker_stack:
    state: present
    name: card-generator-stack
    compose:
      - /home/jenkins/docker-compose.yaml