---
# tasks file for install-modules
- name: Install Packages
  apt: 
    state: latest
    update_cache: true
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3
    - python3-pip