---
# tasks file for docker-compose
- name: Install or upgrade docker-compose
  get_url: 
    url : "https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 'a+x'
    force: yes