all:
  children:
    swarm-manager:
      hosts:
        docker-swarm:
    swarm-workers:
      hosts:
        worker-vm1:
    load-balancer:
      hosts:
        nginx-vm:
  vars:
    ansible_user: welcom
    ansible_ssh_private_key_file: '~/.ssh/id_rsa'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
