- hosts: load-balancer
  become: true
  roles:
    - git
    - nginx

- hosts: swarm-manager
  become: true
  roles:
    - install-modules
    - git
    - docker
    - initialise-swarm
    - docker-compose
    

- hosts: swarm-workers
  become: true
  roles:
    - install-modules
    - git
    - docker
    - add-swarm-worker
    - docker-compose
    
